# Generated by Django 3.2.3 on 2021-05-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicial_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('work_order_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.location')),
                ('work_order_technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.technician')),
            ],
        ),
    ]
