# Generated by Django 3.2.3 on 2021-05-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_technicial_name_technician_technician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.location'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.technician'),
        ),
    ]
