# Generated by Django 3.2.3 on 2021-05-31 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210528_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='scheduler.technician'),
        ),
    ]
